services:
  chatbot-app:
    build: .
    container_name: taxi_driver_chatbot
    ports:
      - "8501:8501"
    env_file:
      - .env
    depends_on:
      - qdrant-db
      - ollama-service
    restart: always
    volumes:
      - chatbot_storage:/app/storage

  qdrant-db:
    image: qdrant/qdrant:latest
    container_name: qdrant_local
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  ollama-service:
    image: ollama/ollama:latest
    container_name: ollama_local
    ports:
      - "11434:11434"
    volumes:
      - ollama_storage:/root/.ollama
    entrypoint: [ "/bin/sh", "-c" ]
    command: 
      - |
        ollama serve &
        sleep 5
        ollama pull llama3.2:latest
        tail -f /dev/null

volumes:
  qdrant_storage:
  ollama_storage:
  chatbot_storage: